# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natsmith < Formula
  desc "CLI tooling for NATS and JetStream"
  homepage "https://sabinadams.github.io/natsmith/"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sabinadams/natsmith/releases/download/v1.2.2/natsmith_1.2.2_darwin_amd64.tar.gz"
      sha256 "5cae4d0871834c3ef4250458e7dae46213c48d1c5ada789ceb9905853ecca92c"

      define_method(:install) do
        bin.install "natsmith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sabinadams/natsmith/releases/download/v1.2.2/natsmith_1.2.2_darwin_arm64.tar.gz"
      sha256 "38352d8fce727a6ff94ca7fc0a1df015d1b9ece643999b710f832912775758a9"

      define_method(:install) do
        bin.install "natsmith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sabinadams/natsmith/releases/download/v1.2.2/natsmith_1.2.2_linux_amd64.tar.gz"
      sha256 "1320706d4ee46766ecd9a5a0e8f77476d2eb0d74af023a376609465951bc89fc"
      define_method(:install) do
        bin.install "natsmith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sabinadams/natsmith/releases/download/v1.2.2/natsmith_1.2.2_linux_arm64.tar.gz"
      sha256 "daeef23bd4743c82fd2874b29d4f39e95fd70c4db52fb125e7969435f49e76da"
      define_method(:install) do
        bin.install "natsmith"
      end
    end
  end

  test do
    system "#{bin}/natsmith", "-h"
  end
end
